spring.application.name=BitacoraDigitalServices

server.port=8081

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

db.name = bitacora_digital
db.host = localhost
db.port = 3306
db.user = root
db.pass = hs35AMl1GKdsG59Z